# Generated by Django 5.2.12 on 2026-03-24 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SFCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active_clients', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sf_coach',
            },
        ),
        migrations.CreateModel(
            name='SFAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('coaching_start_date', models.DateField()),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='salesforce_sim.sfcoach')),
            ],
            options={
                'db_table': 'sf_account',
            },
        ),
        migrations.CreateModel(
            name='SFContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='salesforce_sim.sfaccount')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='salesforce_sim.sfcoach')),
            ],
            options={
                'db_table': 'sf_contact',
            },
        ),
        migrations.CreateModel(
            name='SFAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='salesforce_sim.sfaccount')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='salesforce_sim.sfcoach')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='salesforce_sim.sfcontact')),
            ],
            options={
                'db_table': 'sf_assignment',
                'unique_together': {('coach', 'contact')},
            },
        ),
    ]
