# Generated by Django 4.2.17 on 2026-03-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce_sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfaccount',
            name='assigned_coach',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sfcontact',
            name='assigned_coach',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
