# Generated by Django 4.2.17 on 2026-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('coach_swap', 'Coach Swap'), ('coach_remove', 'Coach Removal'), ('account_remove', 'Account Removal'), ('contact_remove', 'Contact Removal'), ('contact_move', 'Contact Move'), ('bulk_reassign', 'Bulk Reassignment')], max_length=30)),
                ('performed_by', models.CharField(max_length=200)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('affected_entities', models.JSONField(default=list)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemaMigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('old_type', models.CharField(max_length=100)),
                ('new_type', models.CharField(max_length=100)),
                ('old_constraints', models.JSONField(blank=True, default=dict)),
                ('new_constraints', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('migrated', 'Migrated'), ('rolled_back', 'Rolled Back'), ('failed', 'Failed')], default='detected', max_length=20)),
                ('migration_sql', models.TextField(blank=True)),
                ('rollback_sql', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
