# Generated by Django 5.2.12 on 2026-03-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('changes_detected', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('coach_added', 'Coach Added'), ('coach_removed', 'Coach Removed'), ('coach_updated', 'Coach Updated'), ('account_added', 'Account Added'), ('account_removed', 'Account Removed'), ('account_reassigned', 'Account Reassigned'), ('account_updated', 'Account Updated'), ('contact_added', 'Contact Added'), ('contact_removed', 'Contact Removed'), ('contact_reassigned', 'Contact Reassigned'), ('contact_updated', 'Contact Updated'), ('assignment_added', 'Assignment Added'), ('assignment_removed', 'Assignment Removed'), ('assignment_updated', 'Assignment Updated')], max_length=30)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_sf_id', models.UUIDField()),
                ('entity_name', models.CharField(max_length=200)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('coach_name', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='sync.synclog')),
            ],
            options={
                'ordering': ['-detected_at'],
                'managed': True,
            },
        ),
    ]
