# Generated by Django 5.2.12 on 2026-03-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaching', '0001_initial'),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('previous_coach_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('audit_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='briefs', to='sync.auditrecord')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefs', to='coaching.coach')),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='briefs', to='sync.synclog')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
