# Generated by Django 5.2.12 on 2026-03-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_of_sync', models.BooleanField(default=False)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
